# source-hash: adb7ac673a2c8917ab28d637a17885690c81fafa1341ee0d7a31c46814145996
# ^ generated by sync-local-neflib.ps1 from the neflib/include and neflib/src trees, do not edit
# by hand. vcpkg computes its ABI hash from this file's own contents, not from SOURCE_PATH below,
# so this comment is what forces a rebuild whenever the local neflib submodule changes.
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

# Dev-only overlay: build the local "neflib" git submodule checkout instead of downloading a
# tagged release. See README.md "Local development against neflib" for how this is enabled.
get_filename_component(SOURCE_PATH "${CMAKE_CURRENT_LIST_DIR}/../../neflib" ABSOLUTE)

if(NOT EXISTS "${SOURCE_PATH}/src/neflib.vcxproj")
    message(FATAL_ERROR
        "Local neflib submodule not found at '${SOURCE_PATH}'. Run "
        "'git submodule update --init neflib' first, or unset NEFCON_LOCAL_NEFLIB to consume "
        "the published neflib package from the nefarius-vcpkg-registry instead.")
endif()

vcpkg_msbuild_install(
    SOURCE_PATH "${SOURCE_PATH}"
    PROJECT_SUBPATH src/neflib.vcxproj
    RELEASE_CONFIGURATION "Release"
    DEBUG_CONFIGURATION "Debug"
    PLATFORM ${VCPKG_TARGET_ARCHITECTURE}
)

vcpkg_fixup_pkgconfig()

vcpkg_copy_pdbs()

file(COPY
    "${SOURCE_PATH}/include/nefarius/neflib"
    DESTINATION "${CURRENT_PACKAGES_DIR}/include/nefarius"
    FILES_MATCHING PATTERN *.h PATTERN *.hpp)

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
